services:
  postgres:
    image: postgres:16
    container_name: asn-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: asn
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - asn_pg_data:/var/lib/postgresql/data

volumes:
  asn_pg_data: