spring:
  application:
    name: batch-analytics
  profiles:
    active: local

server:
  port: ${BATCH_ANALYTICS_PORT:8082}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{requestId:-}] %logger{36} - %msg%n"
